defmodule Jido.Lib.Github.Actions.IssueTriage.CommentIssue do
  @moduledoc """
  Post the investigation results as a comment on the GitHub issue.
  """

  use Jido.Action,
    name: "comment_issue",
    description: "Post investigation results as a GitHub issue comment",
    schema: [
      owner: [type: :string, required: true],
      repo: [type: :string, required: true],
      provider: [type: :atom, default: :claude],
      issue_number: [type: :integer, required: true],
      run_id: [type: :string, required: true],
      session_id: [type: :string, required: true],
      workspace_dir: [type: :string, required: true],
      investigation: [type: {:or, [:string, nil]}, default: nil],
      investigation_status: [type: {:or, [:atom, nil]}, default: nil],
      investigation_error: [type: {:or, [:string, nil]}, default: nil],
      timeout: [type: :integer, default: 300_000],
      shell_agent_mod: [type: :atom, default: Jido.Shell.Agent]
    ]

  require Logger

  alias Jido.Lib.Github.Actions.IssueTriage.Helpers

  @impl true
  def run(params, _context) do
    agent_mod = params[:shell_agent_mod] || Jido.Shell.Agent
    body = build_comment_body(params)

    body_file = "/tmp/jido_issue_comment_#{params.run_id}.md"
    write_cmd = "cat > #{body_file} << 'JIDO_COMMENT_EOF'\n#{body}\nJIDO_COMMENT_EOF"

    _ =
      Helpers.run(agent_mod, params.session_id, write_cmd, timeout: 10_000)

    cmd =
      "gh issue comment #{params.issue_number} " <>
        "--repo #{params.owner}/#{params.repo} " <>
        "--body-file #{body_file}"

    Logger.info(
      "[CommentIssue] Posting comment to #{params.owner}/#{params.repo}##{params.issue_number}"
    )

    case Helpers.run(agent_mod, params.session_id, cmd, timeout: params[:timeout] || 30_000) do
      {:ok, output} ->
        {:ok,
         Map.merge(Helpers.pass_through(params), %{
           comment_posted: true,
           comment_url: extract_url(output),
           comment_error: nil
         })}

      {:error, reason} ->
        Logger.warning("[CommentIssue] Failed to post comment: #{inspect(reason)}")

        {:ok,
         Map.merge(Helpers.pass_through(params), %{
           comment_posted: false,
           comment_url: nil,
           comment_error: inspect(reason)
         })}
    end
  end

  defp build_comment_body(params) do
    status_emoji = if params[:investigation_status] == :ok, do: "✅", else: "⚠️"
    investigation = params[:investigation] || "No investigation output available."

    """
    ## #{status_emoji} Automated Investigation Report

    #{investigation}

    ---
    <sub>Generated by Jido Issue Triage Bot | Run ID: `#{params.run_id}`</sub>
    """
    |> String.trim()
  end

  defp extract_url(output) do
    case Regex.run(~r{https://github\.com/[^\s]+}, output || "") do
      [url] -> url
      _ -> nil
    end
  end
end
