defmodule Jido.Lib.Github.Actions.PostIssueComment do
  @moduledoc """
  Post either triage findings or PR information back to the source issue.
  """

  use Jido.Action,
    name: "post_issue_comment",
    description: "Post triage or PR status comment to a GitHub issue",
    compensation: [max_retries: 0],
    schema: [
      comment_mode: [type: :atom, required: true],
      owner: [type: :string, required: true],
      repo: [type: :string, required: true],
      provider: [type: :atom, default: :claude],
      issue_number: [type: :integer, required: true],
      run_id: [type: :string, required: true],
      session_id: [type: :string, required: true],
      repo_dir: [type: {:or, [:string, nil]}, default: nil],
      workspace_dir: [type: {:or, [:string, nil]}, default: nil],
      investigation: [type: {:or, [:string, nil]}, default: nil],
      investigation_status: [type: {:or, [:atom, nil]}, default: nil],
      investigation_error: [type: {:or, [:string, nil]}, default: nil],
      branch_name: [type: {:or, [:string, nil]}, default: nil],
      commit_sha: [type: {:or, [:string, nil]}, default: nil],
      pr_url: [type: {:or, [:string, nil]}, default: nil],
      timeout: [type: :integer, default: 300_000],
      shell_agent_mod: [type: :atom, default: Jido.Shell.Agent]
    ]

  require Logger

  alias Jido.Lib.Github.Helpers

  @impl true
  def run(params, _context) do
    agent_mod = params[:shell_agent_mod] || Jido.Shell.Agent
    timeout = params[:timeout] || 300_000
    comment_mode = normalize_comment_mode(params[:comment_mode])

    body = build_comment_body(comment_mode, params)
    body_file = "/tmp/jido_issue_comment_#{comment_mode}_#{params.run_id}.md"
    escaped_body_file = Helpers.escape_path(body_file)

    write_cmd =
      "cat > #{escaped_body_file} << 'JIDO_ISSUE_COMMENT_EOF'\n#{body}\nJIDO_ISSUE_COMMENT_EOF"

    with {:ok, _} <- run_comment_cmd(agent_mod, params, write_cmd, 10_000),
         {:ok, output} <-
           run_comment_cmd(agent_mod, params, gh_comment_cmd(params, escaped_body_file), timeout) do
      {:ok, success_result(comment_mode, params, output)}
    else
      {:error, reason} ->
        Logger.warning("[PostIssueComment] mode=#{comment_mode} failed: #{inspect(reason)}")
        {:ok, failure_result(comment_mode, params, reason)}
    end
  end

  defp normalize_comment_mode(:triage_report), do: :triage_report
  defp normalize_comment_mode(:pr_link), do: :pr_link

  defp normalize_comment_mode(other),
    do: raise(ArgumentError, "Invalid comment_mode: #{inspect(other)}")

  defp gh_comment_cmd(params, escaped_body_file) do
    "gh issue comment #{params.issue_number} --repo #{params.owner}/#{params.repo} --body-file #{escaped_body_file}"
  end

  defp run_comment_cmd(agent_mod, params, cmd, timeout) do
    case params[:repo_dir] do
      dir when is_binary(dir) and dir != "" ->
        Helpers.run_in_dir(agent_mod, params.session_id, dir, cmd, timeout: timeout)

      _ ->
        Helpers.run(agent_mod, params.session_id, cmd, timeout: timeout)
    end
  end

  defp success_result(:triage_report, params, output) do
    Map.merge(Helpers.pass_through(params), %{
      comment_posted: true,
      comment_url: extract_url(output),
      comment_error: nil
    })
  end

  defp success_result(:pr_link, params, _output) do
    Map.merge(Helpers.pass_through(params), %{
      issue_comment_posted: true,
      issue_comment_error: nil
    })
  end

  defp failure_result(:triage_report, params, reason) do
    Map.merge(Helpers.pass_through(params), %{
      comment_posted: false,
      comment_url: nil,
      comment_error: inspect(reason)
    })
  end

  defp failure_result(:pr_link, params, reason) do
    Map.merge(Helpers.pass_through(params), %{
      issue_comment_posted: false,
      issue_comment_error: inspect(reason)
    })
  end

  defp build_comment_body(:triage_report, params) do
    status_emoji = if params[:investigation_status] == :ok, do: "OK", else: "WARN"
    investigation = params[:investigation] || "No investigation output available."

    """
    ## #{status_emoji} Automated Investigation Report

    #{investigation}

    ---
    <sub>Generated by Jido Issue Triage Bot | Run ID: `#{params.run_id}`</sub>
    """
    |> String.trim()
  end

  defp build_comment_body(:pr_link, params) do
    """
    ✅ Automated PR created for this issue.

    - PR: #{params[:pr_url] || "unknown"}
    - Branch: `#{params[:branch_name] || "unknown"}`
    - Commit: `#{params[:commit_sha] || "unknown"}`
    - Run ID: `#{params.run_id}`
    """
    |> String.trim()
  end

  defp extract_url(output) when is_binary(output) do
    case Regex.run(~r{https://github\.com/[^\s]+}, output) do
      [url] -> url
      _ -> nil
    end
  end
end
